eureka:
  client:
    service-url:
      defaultZone: http://bookworm-discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 3000
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true